language: node_js
node_js:
- node
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "2Hrh1BwhIJuZEN6FDTzVNRP52C7IjHJXRyzZc1r8Nxo8nX7UHUE0z7wO+x2BOYLxgbOq5JasGgojNriGg5wixOv1z9I2Z9uyWo8+faeNuQDGYyCcG3I+VeM5TIaoE0Jc8QnCvg1dW8SV/w5OT632yvy4FAJzt9FopIRZHtPUxdr3OVdOh1uxfMQe8U2sI6isjIyST56CjN4eRa5d1k8Gl055uQVgeS1loaCoS/jb+2Or94or1n69QmMxjdKKtynW86dofGYH3WJ6/ky+oSYWlZJ68CuDIYqibV99nxTy/Jl8QYf5p//gCLDGcYkJRWacg1cURA9Ww3DgkF5wFRoG2elGeyBptr1gwJqggCSgZQZIOXDVhM/NoIMiCb+ewOXwHLCnY8Y8AT4YrdPFDvBqrfkq/vf8k6yLY87tNNi6RQI2PpuD4koEhGr8cCTkBNgsfwlSgAqrVHKCyWXWA89Cy47x5F6NS5w1/NdGFMCJI2XJuDndidlc1aJmsz5xVIFncVsw0IW1SSGtMo9opsnXjSYGjXfUM170j7mGxi7wuF1DhKxjRoxENFroq9cto9ZkrAZNZHCQNDvz9OpmGdEvcD+qbgZlQmpF9GZE39jyJwR2wmPSl/t9xfY6EllX+Q13iS3eKmEPxvQaQqIetPMs1hKCER7ZabSBTzZrslvJyLQ="
