language: node_js
node_js:
- node
deploy:
  provider: firebase
  token:
    secure: mSueEZboPPm80qF+kVIgULjj6I4rF5TIuDfzsq5eVgvuC+8E5cplVWFbsA22lh0agTw53B+EJr1lsz2RqqyubXbrQGdivZBL/+yoaL30F9c6PsQFi0VLhP3nJYUuTBEuSVMztILBuNbHUHpiOpqJbuuDUGmBqSfh0F4FVTXBrHTOfKxwfROujEIH3LHMzA9zm3aME01Q7DR/hRvsZOMp2cfbhKIlApliLbeH5KubwBZIiDkd1SZGbz62n323SSvhP4HNi10pHG14Z+mlV6csjXLbDBEIZWPacSzQWUhtiNeZQH7Rg8fLFzCPb7L/M0UcOTgxteTNhohJoQ35VjzlUNR4lFbFCEk/g9OLbiF8QaTFgD29pnW8x1CnA5t8s1z6Q+TQrMe0kNjLAJ4l2wLqJZe3jw4luOCLOFJHZ36Zq/81jEUjPP5dv+60u4jGRNKK9tekqYLu83RdR8Re0XkCuDK8MfqSbi+jCw0w+SBNRQ56RRmw5N4T2lKH083tZaCW3CWAhwwlR8UGilqSbkx/XtNb5O4XMhRo3Nq7AwyTQjsZJa2z9TKXPvMOXWWeGJQF4EKf2WHibyDZPr6PEIhrCMxznb3nOO4K10cG5j6/5wu5NgqhquzIPUXNxo7qX3mHTT1dajgvVHpaQIIFKrRhJYM7LnkrAyIMuvFvCFOQQ90=
  skip_cleanup: true
  